### PR TITLE
backend settings are setup

### PR DESCRIPTION
**Pull request by cbaja**
Backend Settings for the App.

@TransitDigitale/transitiondigitale

### CODE REVIEW

**Comment by jetprog** [comment]
i got a prob with ur version compile... u recommend to use the v7:24.0.0 but in ur code i can see v7:24.1.1. @cbaja quick answer plz

**Comment by KeitelDOG** [comment]
Are you sure Jetro? I'm gonna make a check

**Comment by KeitelDOG** [comment]
You're looking at App Compat @jetprog . It's the build tools version that is supposed to be 24.0.0 :
`buildToolsVersion "24.0.0"`

Unfortunately I cannot really approve the Backendless Settings, I'm not used to backendless enough!

**Comment by cbaja** [comment]
this issue was fixed @jetprog . Your gradle file should be like that. 
gradle

@TransitDigitale/transitiondigitale

**Comment by cbaja** [comment]
@KeitelDOG in this case.
Please merge the both PR. Thanks

@TransitDigitale/transitiondigitale

**Comment by jetprog** [comment]
the backendless settings are ok and i'm sure mr Baja use the correct values for secret-key, version, etc... @KeitelDOG

**Pull request merged**
